# Generated by Django 5.1.4 on 2024-12-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='games_played',
            field=models.PositiveIntegerField(default=0, verbose_name='Сыграно игр'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='time_played',
            field=models.PositiveIntegerField(default=0, verbose_name='Время в игре'),
        ),
    ]
